id: A65067CF1
title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
type: translation
pechas:
- IFCAC142D
- I32D1443B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:51.709824
  last_modified_at: 2023-01-04 11:51:51.709838
  collections:
  - Fifth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IFCAC142D/8846: 49FA
  I32D1443B/282A: 49FA
